### ISSUE TITLE
List Index out of range error

### ISSUE THREAD

**Issue by thehof** [spectacles-ci/spectacles#103]
Hello, 

when running spectacles I get the following error: 

```
$ spectacles sql --config-file configprod.yml
Connected using Looker API 3.1
Looker instance version is 6.22.18
Building LookML project hierarchy for project Guild_Home

====================== Testing 606 explores [batch mode] =======================

Encountered unexpected IndexError: "list index out of range"
Full error traceback logged to logs/logs.txt
```

This is the tail end of the log: 

```
019-11-11 11:43:28,612 DEBUG | Creating async query for guild_external_brandman/etl_retention_detailed_overview/*
2019-11-11 11:43:28,618 DEBUG | list index out of range
Traceback (most recent call last):
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/cli.py", line 120, in wrapper
    return function(*args, **kwargs)
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/cli.py", line 176, in main
    args.mode,
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/cli.py", line 413, in run_sql
    errors = runner.validate_sql(explores, mode)
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/runner.py", line 42, in validate_sql
    errors = sql_validator.validate(mode)
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/validators.py", line 214, in validate
    errors = self._query(mode)
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/validators.py", line 254, in _query
    query_task_ids = list(loop.run_until_complete(asyncio.gather(*tasks)))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/validators.py", line 365, in _query_explore
    session, model.name, explore.name, dimensions
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/Users/jessehofmann/virtualenvs/py37/lib/python3.7/site-packages/spectacles/client.py", line 349, in create_query
    "*" if len(dimensions) > 1 else dimensions[0],
IndexError: list index out of range
2019-11-11 11:43:28,626 ERROR | Encountered unexpected IndexError: "list index out of range"
Full error traceback logged to logs/logs.txt

For support, please create an issue at https://github.com/spectacles-ci/spectacles/issues
```

Thanks!

**Comment by joshtemple** [comment]
Can you try installing from `master` in this repo and seeing if that solves it? This should be fixed by #60.

If you want to use pip directly instead of cloning, you can do:
```
pip install --force-reinstall git+git://github.com/spectacles-ci/spectacles.git
```
(the `--force-reinstall` here is to overwrite your existing install with the one from GitHub, even though the version will be the same)
