### ISSUE TITLE
Encountered unexpected AttributeError: "'NoneType' object has no attribute 'split'"

### ISSUE THREAD

**Issue by dihnatsyeu** [spectacles-ci/spectacles#429]
The issue was raised during the spectacles assert invocation

2021-10-15 11:56:54,791 DEBUG | 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/cli.py", line 152, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/cli.py", line 260, in main
    run_assert(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/utils.py", line 61, in timed_function
    result = fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/cli.py", line 655, in run_assert
    results = runner.validate_data_tests(branch, commit_ref, explores, exclude)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/runner.py", line 255, in validate_data_tests
    results = validator.validate()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spectacles/validators/data_test.py", line 58, in validate
    project, file_path = error["file_path"].split("/", 1)
AttributeError: 'NoneType' object has no attribute 'split'
2021-10-15 11:56:54,794 ERROR | 
Encountered unexpected AttributeError: "'NoneType' object has no attribute 'split'"

**Comment by joshtemple** [comment]
Hi @dihnatsyeu, can you confirm you still encounter this issue on the latest version of Spectacles? Thanks!

**Comment by joshtemple** [comment]
Closing this issue due to inactivity. Please feel free to reopen it if you're still encountering this problem!
