### ISSUE TITLE
AttribueError in incremental sql validation

### ISSUE THREAD

**Issue by edkent** [spectacles-ci/spectacles#599]
Hey, I'm trying out the 2.3.0rc1 release.

Running sql validation in incremental mode fails with the below error:

2022-07-22 12:42:35,392 DEBUG | The connection pool was closed while 42 HTTP requests/responses were still in-flight.
Traceback (most recent call last):
  File "/usr/local/autotrader/lib/python3.8/site-packages/spectacles/cli.py", line 938, in run_sql
    results = await runner.validate_sql(
  File "/usr/local/autotrader/lib/python3.8/site-packages/spectacles/runner.py", line 309, in validate_sql
    compiled_explores = await asyncio.gather(
  File "/usr/local/autotrader/lib/python3.8/site-packages/spectacles/validators/sql.py", line 126, in compile_explore
    raise AttributeError(
AttributeError: Explore object is missing dimensions, meaning this query won't have fields and will error. Often this happens because you didn't include dimensions when you built the project.

**Comment by joshtemple** [comment]
Hey @edkent! Thanks for testing this out for us. I've seen a similar issue with another customer of ours. We're jumping on a call soon to debug, so I'll hopefully have an updated version for you to try soon. Stay tuned!

**Comment by joshtemple** [comment]
@edkent, do you mind installing from my branch and confirming this issue is fixed?

The install command will be:
```
pip install --force-reinstall git+https://git@github.com/spectacles-ci/spectacles.git@feature/async
```

**Comment by edkent** [comment]
No problem, looking forward to the speed improvements!

Yep, that's sorted it!

**Comment by joshtemple** [comment]
Great! I've uploaded the new release to PyPi under as `2.3.0rc2` if you'd like to pin to that. Please let us know here or over in Slack what kind of speedups you're seeing!
