### ISSUE TITLE
AttributeError "Explore object is missing dimensions" without which Explorer is errored

### ISSUE THREAD

**Issue by tucker19** [spectacles-ci/spectacles#624]
Hi, 

Using Spectacles `2.2.0`. I am working on a system where we use Spectacles to check close to 250 Explorers. We have noticed this error
```
2022-08-24 13:53:29,545 DEBUG | Explore object is missing dimensions, meaning this query won't have fields and will error. Often this happens because you didn't include dimensions when you built the project.
Traceback (most recent call last):
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/cli.py", line 153, in wrapper
    return function(*args, **kwargs)
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/cli.py", line 272, in main
    run_sql(
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/utils.py", line 61, in timed_function
    result = fn(*args, **kwargs)
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/cli.py", line 890, in run_sql
    results = runner.validate_sql(
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/runner.py", line 296, in validate_sql
    base_tests = validator.create_tests(
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/validators/sql.py", line 207, in create_tests
    test = self._create_explore_test(explore, compile_sql, chunk_size)
  File "/Users/adam.howell/miniconda3/lib/python3.9/site-packages/spectacles/validators/sql.py", line 219, in _create_explore_test
    raise AttributeError(
AttributeError: Explore object is missing dimensions, meaning this query won't have fields and will error. Often this happens because you didn't include dimensions when you built the project.
2022-08-24 13:53:29,549 ERROR | 
Encountered unexpected AttributeError: "Explore object is missing dimensions, meaning this query won't have fields and will error. Often this happens because you didn't include dimensions when you built the project."
Full error traceback logged to file.
```

If I am understanding the log itself correctly is the last `async query` created the Explorer that is causing this? Example looks like this 
```
2022-08-24 13:53:29,428 DEBUG | Creating async query for in_game/checked_in/*
2022-08-24 13:53:29,544 DEBUG | Query for in_game/checked_in/* created as query 297099
```
If possible it would be a big help in this error is to say specifically call out the Explorer that is raising the exception if I am incorrect about the last `async query` comment.

Note: I have checked the Explorer for `checked_in` within Looker and to me I am seeing dimensions so not sure what more could be causing this issue.

**Comment by DylanBaker** [comment]
Hi @tucker19. Thanks for creating the issue. 

This logging is actually a bit unhelpful, as I believe this error relates to the _next_ query being created. If you scroll up earlier in the logs, you'll see some logging about fetching all dimensions. In those logs, you should be able to get what the next explore would have been, as it should be the one after `in_game/checked_in`. Is it possible that one doesn't have dimensions?

**Comment by DylanBaker** [comment]
This error messaging improves quite a bit in 2.3.0. We're hoping to have that released shortly. There's a release candidate available today if you wanted to try that.

**Comment by tucker19** [comment]
> 

Thank you for this explanation. That helped so much and found the issue. It would still be helpful that in the exception raised if it would have put the actual item that failed though to then not need to dig through the logs as much. Again thanks for the help.
