### ISSUE TITLE
Possible race condition in httpx requests

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#658]
We are occasionally encountering this error from `httpcore`, which is called by `httpx`, the library that we use to make async HTTP requests.

I've only been able to find [this recent issue in httpcore](https://github.com/encode/httpcore/issues/613) and this [very old issue in httpx](https://github.com/encode/httpx/issues/689).

It's still not clear to me what's happening, but it seems to be an issue with connection pooling.

```
Traceback (most recent call last):
  File "/app/src/engine_build/run.py", line 258, in run_spectacles
    run_validator_result = await run_validator(
  File "/app/src/engine_build/run.py", line 168, in run_validator
    result = await runner.validate_sql(
  File "/usr/local/lib/python3.10/site-packages/spectacles/runner.py", line 400, in validate_sql
    await validator.search(
  File "/usr/local/lib/python3.10/site-packages/spectacles/validators/sql.py", line 228, in search
    raise result
  File "/usr/local/lib/python3.10/site-packages/spectacles/validators/sql.py", line 258, in _run_query
    task_id = await self.client.create_query_task(query.query_id)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/spectacles/client.py", line 743, in create_query_task
    response = await self.post(
  File "/usr/local/lib/python3.10/site-packages/spectacles/client.py", line 153, in post
    return await self.request("POST", url, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/spectacles/client.py", line 147, in request
    return await self.async_client.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 221, in handle_async_request
    await self._attempt_to_acquire_connection(status)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 178, in _attempt_to_acquire_connection
    status.set_connection(connection)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 22, in set_connection
    assert self.connection is None
AssertionError
```

**Comment by joshtemple** [comment]
We've hopefully solved this by downgrading httpcore, see notes in #661.
